spring:
  application:
    name: eureka-client
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/cloud
  redis:
    host: localhost
    port: 6379
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.auctionservice.dao.entity
server:
  port: 7002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka
